### PR TITLE
Add fidis computer with ch-315 reservation (+ codes).

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Comment by sphuber** [comment]
Just a high-level question on the scope of this repository that this PR triggered for me: this addition seems to me to be very specific as it targets an explicit allocation on a single machine, so only people with access to that allocation can use these configurations. I am not sure how many people this would service, but do we have any "limits" on what gets accepted here, or can anyone add any configuration? Could I add a configuration that is just useful for me alone, just to help me simplify configuring my AiiDA install on multiple machines? I am not sure if this has already been discussed and if there is a consensus @ltalirz

**Comment by yakutovicha** [comment]
> Just a high-level question on the scope of this repository that this PR triggered for me: this addition seems to me to be very specific as it targets an explicit allocation on a single machine, so only people with access to that allocation can use these configurations.

That is correct.

> I am not sure how many people this would service, but do we have any "limits" on what gets accepted here, or can anyone add any configuration? Could I add a configuration that is just useful for me alone, just to help me simplify configuring my AiiDA install on multiple machines? I am not sure if this has already been discussed and if there is a consensus @ltalirz

My current understanding is that anyone can add any configuration. The purpose (again, my interpretation) is to simplify the computer/code setup as much as possible. So to me, that would be completely fine to have multiple daint setups for different daint reservations. Let's maybe have a separate issue to discuss the scope of this repo?

**Comment by yakutovicha** [comment]
There is already an issue about that, actually: https://github.com/aiidateam/aiida-code-registry/issues/8

**Comment by yakutovicha** [comment]
As we agreed with @ltalirz I am going to go ahead with merging the PR, while the discussion initiated by @sphuber can be continued in the issue #8

**Pull request merged**
