### PR TITLE
Improve: replace put_your_username with {username} template.

### PR DESCRIPTION
**Pull request by yakutovicha**

### CODE REVIEW

**Comment by mbercx** [comment]
Thanks @yakutovicha. Does this sort of templating actually work in the configuration file? I just tried and the computer test failed. Or is this just because it looks cleaner than `put_your_username`? ^^

**Comment by yakutovicha** [comment]
> Thanks @yakutovicha. Does this sort of templating actually work in the configuration file? I just tried and the computer test failed. Or is this just because it looks cleaner than `put_your_username`? ^^

Here I am trying to move from something that cannot be templated to something that can be (at least) in the AiiDAlab app.

**Comment by yakutovicha** [comment]
We can also agree on applying jinja2-like templating here. That is also an option.

**Comment by mbercx** [comment]
> We can also agree on applying jinja2-like templating here. That is also an option.

Hmm, not sure what's best here. On the one hand the current suggested notation is consistent with the templating we use in the setup YAML files. On the other hand that might confuse some users (😙) that this will work directly with `verdi computer configure`. If you plan to use jinja, I'd switch to that notation. If not, feel free to merge as is.

**Review by mbercx — APPROVED** [review]

**Pull request merged**
