### PR TITLE
Update ch315 course setup

### PR DESCRIPTION
**Pull request by mpougin**
I updated the setup for the epfl course. @chrisjsewell or @mbercx can you please merge as discussed? I will test it with AiiDAlab once it's merged. Thank you

### CODE REVIEW

**Review by chrisjsewell — APPROVED** [review]
👌

**Comment by mpougin** [comment]
thanks chris :)

**Comment by mpougin** [comment]
the computer is not showing up in aiidalab. Do I have to add a subfolder lsmosrv4 for the computer setup files?

**Comment by mbercx** [comment]
Hmm, not sure. I haven't updated these for AiiDAlab. Maybe @yakutovicha has an idea?

**Pull request merged**
